config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'chatroom#index'
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  delete 'logout', to: 'sessions#destroy'
  post 'messages', to: 'messages#create'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	validates :body, presence: true
	scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :messages
	validates :username, presence: true, length: { minimum: 2, 
				maximum: 50 }, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:error]= 'You must be logged to perform that action'
			redirect_to login_path
		end
	end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
	before_action :require_user

	def index
		@messages=Message.custom_display
		@message = Message.new
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_user

	def create
		@message=Message.new( body: params[:message][:body], user: current_user )

		if @message.save
			ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(@message)
		end		
		redirect_to root_path
	end


	private

	def message_render(message)
		render(partial: 'message', locals:{message: message})
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
		
	before_action :logged_in_redirect, only: [ :new, :create ]

	def new
	end

	def create
		user=User.find_by(username:params[:session][:username])
		if (user && user.authenticate(params[:session][:password]))
			session[:user_id]=user.id
			flash[:info]='You have ben sucessfully logged in'
			redirect_to root_path
		else
			flash.now[:negative]='Incorect password or username '
			render 'new'
		end
	end

	def destroy
		session[:user_id]= nil
		flash[:success]= 'You have successfully logged out '
		redirect_to root_path
	end


	private
	
	def logged_in_redirect
		if logged_in?
			flash[:error]='You are already logged in'
			redirect_to root_path
		end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
		

	def new
		@user=User.new
	end


	def create
		@user=User.new(user_params)
		if @user.save
			flash[:info]='You have ben sucessfully signed up'
			session[:user_id]=@user.id
			redirect_to root_path
		else
			render "new"
		end
	end


	private
	def user_params
		params.require(:user).permit(:username, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def show_link(link_text, link_source)
  		link_to("#{content_tag :i, nil, class: 'signup white icon'} #{link_text}".html_safe,
    	link_source, class: "ui big orange button")
	end
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="inverted orange circular coffee icon"></i>

  Friends
</h2>

<%= render 'layouts/flash' %>







<% if @message.errors.any? %>
  <div class="ui negative message">
  	 <%= pluralize(@message.errors.count,"error")%> prohibit article from being created
    <i class="close icon"></i>
    <div class="header">
      
    </div>  
  </div>
	
<% end %>












<div class="ui two column grid">
    <div class="ten wide column">
		<div class='ui fluid raised card chatbox'>
			<div class="content" id="messages"> 

				<div class="ui feed" id="message-container">
				  	<%= render @messages %>
				</div>
			</div>
			

			<div class="extra content">
				<%= form_for @message, html: {class: "ui reply form"}, url: messages_path, remote: true do |f| %>
				  <div class="field">
					<div class="ui fluid icon input">
						<%= f.text_field :body, type:"text", placeholder:'Enter a message' %>
            			<%= button_tag( :class => "ui orange small submit button") do %> &nbsp;
              			<i class="bordered inverted orange edit icon"></i> 
            			<% end %>
            								
					</div>
				  </div>
				<% end %>
			</div>


		</div>	




    </div>

    <div class="six wide column">
		<div class='ui fluid raised card chatbox'>
			<div class="content"> 
				<div class="ui inverted vertical menu s-menu">
				  <a class="active item">
				    Home
				  </a>
				  <a class="item">
				    Messages 
				  </a>
				  <a class="item">
				    Friends
				  </a>
				</div>
			</div>


		</div>
		






    </div>
 
</div>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
	<% flash.each do |type, msg| %>
	  <div class="ui <%= type %> message">
	    <i class="close icon"></i>
	    <div class="header">
	      <%= msg %>
	    </div>  
	  </div>
	<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  
<div class="ui small inverted menu">
  <div class="ui container">
    
    <%= link_to 'Chat box', root_path, class:'active item' %>
    
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Log out', logout_path, method: :delete,class:"item" %>
          <% else %>
            <%= link_to 'Log in', login_path, class:'item' %>
            <a class="item">Sign up</a>
          <% end %>
        </div>
      </div>

      <% if !logged_in? %>
        <div class="item">
            <%= link_to 'Sing Up', signup_path, class:'ui orange button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
	<div class="content">
	  <div class="summary">
	     <em><%= message.user.username %>:</em>
	     <%= message.body %>
	  </div>
	</div>
</div>

app/views/users/new.html.erb
<h2 class="ui center aligned icon header">
	Welcome in message me app
  <i class="inverted orange circular power off icon log-in"></i>

  Sign up
</h2>


<div class='flash-space'>
  <%= render 'layouts/flash' %>
</div>



<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column signup">
      <div class="ui form">
        <%= form_for @user, url: signup_path do |f| %>

          <div class="field">
            <%= f.label "username" %>
            <div class="ui left icon input">
              <%=f.text_field :username, type:"text",placeholder:'Username' %>
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field">
            <%= f.label "Password" %>
            <div class="ui left icon input">
              <%=f.password_field :password, type:'password' %>
              <i class="lock icon"></i>
            </div>
          </div>
            <%= button_tag( :class => "ui orange submit button") do %>
              <i class='handshake outline icon'></i>  Log in 
            <% end %>
        <% end %>
      </div>
    </div>
    
  </div>
  
</div>